### PR TITLE
Docs

### PR DESCRIPTION
**Pull request by LemonBaba**

### CODE REVIEW

**Comment by s-yadav** [comment]
Highlight.js is not working for all of the code snippets.

**Comment by s-yadav** [comment]
Design is fine for v1. We can merge this few CSS fixes. I will make those.
Also, let's explore on.
- Theme for doc.
- Markdown docs (Need to see if interactive markdown documentation tool is there for vanilla js projects)

**Comment by LemonBaba** [comment]
> Highlight.js is not working for all of the code snippets.

Let me quickly fix this

**Comment by s-yadav** [comment]
It's not working for me on the latest commit as well. I see this error.
https://www.dropbox.com/s/fjqr2woqe9hvacx/Screenshot%202019-09-02%2017.57.14.png?dl=0

**Comment by LemonBaba** [comment]
I don't see this error. Did you build and serve using jekyll?

**Comment by s-yadav** [comment]
No I just did `python -m SimpleHTTPServer`. Will try with jekyll as well.

**Comment by s-yadav** [comment]
With Jekyll it worked. I have made some small changes on html(removed h tags from nav links. ) And added some margins. 
Will merge this. Thanks

**Pull request merged**
